#!/bin/sh
#
# Startup script for dnsupdate
#
# chkconfig: 2345 65 38
# description: DNS Updater for A and AAAA records
# processname: dnsupdate
# pidfile: /var/run/dnsupdate.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# See how we were called.
case "$1" in
  start)
        echo -n "Starting dnsupdate: "
        daemon /usr/bin/dnsupdate --pidfile /var/run/dnsupdate.pid
        RETVAL=$?
        echo
        ;;
  stop)
        echo -n "Stopping dnsupdate: "
        killproc dnsupdate
        rm -f /var/run/dnsupdate.pid
        RETVAL=$?
        echo
        ;;
  status)
        status /usr/bin/dnsupdate
        RETVAL=$?
        ;;
  restart)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
  reload)
  		echo -n "Reloading dnsupdate: "
        killproc dnsupdate -HUP
        RETVAL=$?
        echo
        ;;
  		
  *)
        echo "Usage: dnsupdate {start|stop|status|restart|reload}"
        exit 1
esac

exit $RETVAL
